fix: `issues` incremental replication (#302)
* Fix incremental replication for `issues`

* Flag `issues` stream as sorted

* The Jira API returns more granular timestamps than JQL supports querying with, so we cannot check the stream is sorted due to the potential for issues to be re-fetched when requesting updates at the minute level

```
singer_sdk.exceptions.InvalidStreamSortException: Unsorted data detected in stream. Latest value '2026-02-17T10:29:17.686+0000' is smaller than previous max '2026-02-17T10:29:44.474+0000'.
```

* Make mypy happy

* Comment typo

* Add some tests

* Ignore some extra Ruff rules for test files

* chore: Make mypy happy

Signed-off-by: Edgar Ramírez-Mondragón <edgarrm358@gmail.com>

* Re-enable `ANN201` to align with mypy expectations

---------

Signed-off-by: Edgar Ramírez-Mondragón <edgarrm358@gmail.com>
Co-authored-by: Edgar Ramírez-Mondragón <edgarrm358@gmail.com>